// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlr6FdZKwPHCmLGnnPjJs6_Ktdqdua_6M',
    appId: '1:168987278677:web:4b2f61a97c159542b743dc',
    messagingSenderId: '168987278677',
    projectId: 'hobbycove',
    authDomain: 'hobbycove.firebaseapp.com',
    storageBucket: 'hobbycove.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0lGc5hj_e8uFs0zpDXaDkWz0DPSV584',
    appId: '1:168987278677:android:db5e99f7901884bdb743dc',
    messagingSenderId: '168987278677',
    projectId: 'hobbycove',
    storageBucket: 'hobbycove.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ZdY47iHv2zIbWhA7JB_VuCeVAiFGsuk',
    appId: '1:168987278677:ios:84fd254c3d9e62d9b743dc',
    messagingSenderId: '168987278677',
    projectId: 'hobbycove',
    storageBucket: 'hobbycove.appspot.com',
    iosClientId: '168987278677-6762msoi6pe5hoe3d7qvmtraklm328kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbycoveG1t1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ZdY47iHv2zIbWhA7JB_VuCeVAiFGsuk',
    appId: '1:168987278677:ios:84fd254c3d9e62d9b743dc',
    messagingSenderId: '168987278677',
    projectId: 'hobbycove',
    storageBucket: 'hobbycove.appspot.com',
    iosClientId: '168987278677-6762msoi6pe5hoe3d7qvmtraklm328kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbycoveG1t1',
  );
}
